package bean;
// Generated 11/10/2025 15:20:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MlrClientes generated by hbm2java
 */
@Entity
@Table(name="mlr_clientes"
    ,catalog="db_maria_rosa"
)
public class MlrClientes  implements java.io.Serializable {


     private int mlrIdClientes;
     private String mlrNome;
     private String mlrCpf;
     private String mlrTelefone;
     private String mlrEmail;
     private Date mlrDataNascimento;
     private String mlrEndereco;
     private String mlrBairro;
     private String mlrCidade;
     private int mlrEstado;
     private String mlrCep;
     private Date mlrDataCadastro;
     private Double mlrLimiteCredito;
     private String mlrObservacoes;
     private String mlrAtivo;


    public MlrClientes() {
    }
     public MlrClientes(int mlrIdClientes) {
        this.mlrIdClientes = mlrIdClientes;
    }


	
    public MlrClientes(int mlrIdClientes, String mlrNome, String mlrCpf, String mlrTelefone, String mlrEmail, Date mlrDataNascimento, String mlrEndereco, String mlrBairro, String mlrCidade, int mlrEstado, String mlrCep, Date mlrDataCadastro, Double mlrLimiteCredito, String mlrObservacoes, String mlrAtivo) {
        this.mlrIdClientes = mlrIdClientes;
        this.mlrNome = mlrNome;
        this.mlrCpf = mlrCpf;
        this.mlrTelefone = mlrTelefone;
        this.mlrEmail = mlrEmail;
        this.mlrDataNascimento = mlrDataNascimento;
        this.mlrEndereco = mlrEndereco;
        this.mlrBairro = mlrBairro;
        this.mlrCidade = mlrCidade;
        this.mlrEstado = mlrEstado;
        this.mlrCep = mlrCep;
        this.mlrDataCadastro = mlrDataCadastro;
        this.mlrLimiteCredito = mlrLimiteCredito;
        this.mlrObservacoes = mlrObservacoes;
        this.mlrAtivo = mlrAtivo;
    }
    public MlrClientes(int mlrIdClientes, String mlrNome, String mlrCpf, String mlrTelefone, String mlrEmail, Date mlrDataNascimento, String mlrEndereco, String mlrBairro, String mlrCidade, int mlrEstado, String mlrCep, Date mlrDataCadastro, Double mlrLimiteCredito, String mlrObservacoes, String mlrAtivo, Set mlrVendases) {
       this.mlrIdClientes = mlrIdClientes;
       this.mlrNome = mlrNome;
       this.mlrCpf = mlrCpf;
       this.mlrTelefone = mlrTelefone;
       this.mlrEmail = mlrEmail;
       this.mlrDataNascimento = mlrDataNascimento;
       this.mlrEndereco = mlrEndereco;
       this.mlrBairro = mlrBairro;
       this.mlrCidade = mlrCidade;
       this.mlrEstado = mlrEstado;
       this.mlrCep = mlrCep;
       this.mlrDataCadastro = mlrDataCadastro;
       this.mlrLimiteCredito = mlrLimiteCredito;
       this.mlrObservacoes = mlrObservacoes;
       this.mlrAtivo = mlrAtivo;
    }
   
     @Id 

    
    @Column(name="mlr_id_clientes", unique=true, nullable=false)
    public int getMlrIdClientes() {
        return this.mlrIdClientes;
    }
    
    public void setMlrIdClientes(int mlrIdClientes) {
        this.mlrIdClientes = mlrIdClientes;
    }

    
    @Column(name="mlr_nome", nullable=true, length=100)
    public String getMlrNome() {
        return this.mlrNome;
    }
    
    public void setMlrNome(String mlrNome) {
        this.mlrNome = mlrNome;
    }

    
    @Column(name="mlr_cpf", nullable=true, length=14)
    public String getMlrCpf() {
        return this.mlrCpf;
    }
    
    public void setMlrCpf(String mlrCpf) {
        this.mlrCpf = mlrCpf;
    }

    
    @Column(name="mlr_telefone", nullable=true, length=15)
    public String getMlrTelefone() {
        return this.mlrTelefone;
    }
    
    public void setMlrTelefone(String mlrTelefone) {
        this.mlrTelefone = mlrTelefone;
    }

    
    @Column(name="mlr_email", nullable=true, length=100)
    public String getMlrEmail() {
        return this.mlrEmail;
    }
    
    public void setMlrEmail(String mlrEmail) {
        this.mlrEmail = mlrEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mlr_data_nascimento", nullable=true, length=10)
    public Date getMlrDataNascimento() {
        return this.mlrDataNascimento;
    }
    
    public void setMlrDataNascimento(Date mlrDataNascimento) {
        this.mlrDataNascimento = mlrDataNascimento;
    }

    
    @Column(name="mlr_endereco", nullable=true, length=100)
    public String getMlrEndereco() {
        return this.mlrEndereco;
    }
    
    public void setMlrEndereco(String mlrEndereco) {
        this.mlrEndereco = mlrEndereco;
    }

    
    @Column(name="mlr_bairro", nullable=true, length=50)
    public String getMlrBairro() {
        return this.mlrBairro;
    }
    
    public void setMlrBairro(String mlrBairro) {
        this.mlrBairro = mlrBairro;
    }

    
    @Column(name="mlr_cidade", nullable=true, length=50)
    public String getMlrCidade() {
        return this.mlrCidade;
    }
    
    public void setMlrCidade(String mlrCidade) {
        this.mlrCidade = mlrCidade;
    }

    
    @Column(name="mlr_estado", nullable=true, length=2)
    public int getMlrEstado() {
        return this.mlrEstado;
    }
    
    public void setMlrEstado(int mlrEstado) {
        this.mlrEstado = mlrEstado;
    }

    
    @Column(name="mlr_cep", nullable=true, length=9)
    public String getMlrCep() {
        return this.mlrCep;
    }
    
    public void setMlrCep(String mlrCep) {
        this.mlrCep = mlrCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mlr_data_cadastro", nullable=true, length=10)
    public Date getMlrDataCadastro() {
        return this.mlrDataCadastro;
    }
    
    public void setMlrDataCadastro(Date mlrDataCadastro) {
        this.mlrDataCadastro = mlrDataCadastro;
    }

    
    @Column(name="mlr_limite_credito", nullable=true, precision=10)
    public Double getMlrLimiteCredito() {
        return this.mlrLimiteCredito;
    }
    
    public void setMlrLimiteCredito(Double mlrLimiteCredito) {
        this.mlrLimiteCredito = mlrLimiteCredito;
    }

    
    @Column(name="mlr_observacoes", nullable=true, length=50)
    public String getMlrObservacoes() {
        return this.mlrObservacoes;
    }
    
    public void setMlrObservacoes(String mlrObservacoes) {
        this.mlrObservacoes = mlrObservacoes;
    }

    
    @Column(name="mlr_ativo", nullable=true, length=1)
    public String getMlrAtivo() {
        return this.mlrAtivo;
    }
    
    public void setMlrAtivo(String mlrAtivo) {
        this.mlrAtivo = mlrAtivo;
    }
    @Override
    public String toString() {
        return this.mlrNome;
    }

}


