package bean;
// Generated 11/10/2025 15:20:24 by Hibernate Tools 4.3.1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MlrFuncionarios generated by hbm2java
 */
@Entity
@Table(name="mlr_funcionarios"
    ,catalog="db_maria_rosa"
)
public class MlrFuncionarios  implements java.io.Serializable {


     private int mlrIdFuncionarios;
     private String mlrNome;
     private String mlrCpf;
     private String mlrTelefone;
     private String mlrEmail;
     private String mlrCargo;
     private Double mlrSalario;

    public MlrFuncionarios() {
    }

	
    public MlrFuncionarios(int mlrIdFuncionarios) {
        this.mlrIdFuncionarios = mlrIdFuncionarios;
    }
    public MlrFuncionarios(int mlrIdFuncionarios, String mlrNome, String mlrCpf, String mlrTelefone, String mlrEmail, String mlrCargo, Double mlrSalario, Set mlrVendases) {
       this.mlrIdFuncionarios = mlrIdFuncionarios;
       this.mlrNome = mlrNome;
       this.mlrCpf = mlrCpf;
       this.mlrTelefone = mlrTelefone;
       this.mlrEmail = mlrEmail;
       this.mlrCargo = mlrCargo;
       this.mlrSalario = mlrSalario;
    }
   
     @Id 

    
    @Column(name="mlr_id_funcionarios", unique=true, nullable=false)
    public int getMlrIdFuncionarios() {
        return this.mlrIdFuncionarios;
    }
    
    public void setMlrIdFuncionarios(int mlrIdFuncionarios) {
        this.mlrIdFuncionarios = mlrIdFuncionarios;
    }

    
    @Column(name="mlr_nome", length=100)
    public String getMlrNome() {
        return this.mlrNome;
    }
    
    public void setMlrNome(String mlrNome) {
        this.mlrNome = mlrNome;
    }

    
    @Column(name="mlr_cpf", length=14)
    public String getMlrCpf() {
        return this.mlrCpf;
    }
    
    public void setMlrCpf(String mlrCpf) {
        this.mlrCpf = mlrCpf;
    }

    
    @Column(name="mlr_telefone", length=15)
    public String getMlrTelefone() {
        return this.mlrTelefone;
    }
    
    public void setMlrTelefone(String mlrTelefone) {
        this.mlrTelefone = mlrTelefone;
    }

    
    @Column(name="mlr_email", length=100)
    public String getMlrEmail() {
        return this.mlrEmail;
    }
    
    public void setMlrEmail(String mlrEmail) {
        this.mlrEmail = mlrEmail;
    }

    
    @Column(name="mlr_cargo", length=50)
    public String getMlrCargo() {
        return this.mlrCargo;
    }
    
    public void setMlrCargo(String mlrCargo) {
        this.mlrCargo = mlrCargo;
    }

    
    @Column(name="mlr_salario", precision=10)
    public Double getMlrSalario() {
        return this.mlrSalario;
    }
    
    public void setMlrSalario(Double mlrSalario) {
        this.mlrSalario = mlrSalario;
    }



}


