package bean;
// Generated 11/10/2025 15:20:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MlrProdutos generated by hbm2java
 */
@Entity
@Table(name="mlr_produtos"
    ,catalog="db_maria_rosa"
)
public class MlrProdutos  implements java.io.Serializable {


     private int mlrIdProdutos;
     private String mlrNome;
     private String mlrDescricao;
     private int mlrCategoria;
     private Double mlrPreco;
     private String mlrMarca;
     private Date mlrDataValidade;

    public MlrProdutos() {
    }
    

	
    public MlrProdutos(int mlrIdProdutos) {
        this.mlrIdProdutos = mlrIdProdutos;
    }
    public MlrProdutos(int mlrIdProdutos, String mlrNome, String mlrDescricao, int mlrCategoria, Double mlrPreco, String mlrMarca, Date mlrDataValidade, Set mlrVendasProdutoses) {
       this.mlrIdProdutos = mlrIdProdutos;
       this.mlrNome = mlrNome;
       this.mlrDescricao = mlrDescricao;
       this.mlrCategoria = mlrCategoria;
       this.mlrPreco = mlrPreco;
       this.mlrMarca = mlrMarca;
       this.mlrDataValidade = mlrDataValidade;
    }
   
     @Id 

    
    @Column(name="mlr_id_produtos", unique=true, nullable=false)
    public int getMlrIdProdutos() {
        return this.mlrIdProdutos;
    }
    
    public void setMlrIdProdutos(int mlrIdProdutos) {
        this.mlrIdProdutos = mlrIdProdutos;
    }

    
    @Column(name="mlr_nome", length=100)
    public String getMlrNome() {
        return this.mlrNome;
    }
    
    public void setMlrNome(String mlrNome) {
        this.mlrNome = mlrNome;
    }

    
    @Column(name="mlr_descricao", length=50)
    public String getMlrDescricao() {
        return this.mlrDescricao;
    }
    
    public void setMlrDescricao(String mlrDescricao) {
        this.mlrDescricao = mlrDescricao;
    }

    
    @Column(name="mlr_categoria", length=50)
    public int getMlrCategoria() {
        return this.mlrCategoria;
    }
    
    public void setMlrCategoria(int mlrCategoria) {
        this.mlrCategoria = mlrCategoria;
    }

    
    @Column(name="mlr_preco", precision=10)
    public Double getMlrPreco() {
        return this.mlrPreco;
    }
    
    public void setMlrPreco(Double mlrPreco) {
        this.mlrPreco = mlrPreco;
    }

    
    @Column(name="mlr_marca", length=100)
    public String getMlrMarca() {
        return this.mlrMarca;
    }
    
    public void setMlrMarca(String mlrMarca) {
        this.mlrMarca = mlrMarca;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mlr_data_validade", length=10)
    public Date getMlrDataValidade() {
        return this.mlrDataValidade;
    }
    
    public void setMlrDataValidade(Date mlrDataValidade) {
        this.mlrDataValidade = mlrDataValidade;
    }
    

    @Override
    public String toString() {
        return this.mlrNome;
    }

}


