package bean;
// Generated 11/10/2025 15:20:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MlrUsuarios generated by hbm2java
 */
@Entity
@Table(name="mlr_usuarios"
    ,catalog="db_maria_rosa"
)
public class MlrUsuarios  implements java.io.Serializable {


     private int mlrIdUsuarios;
     private String mlrNome;
     private String mlrCpf;
     private Date mlrDataNascimento;
     private String mlrSenha;
     private int mlrNivel;
     private String mlrApelido;
     private String mlrAtivo;

    public MlrUsuarios() {
    }

	
    public MlrUsuarios(int mlrIdUsuarios, String mlrNome, String mlrCpf, String mlrSenha, int mlrNivel, String mlrApelido, String mlrAtivo) {
        this.mlrIdUsuarios = mlrIdUsuarios;
        this.mlrNome = mlrNome;
        this.mlrCpf = mlrCpf;
        this.mlrSenha = mlrSenha;
        this.mlrNivel = mlrNivel;
        this.mlrApelido = mlrApelido;
        this.mlrAtivo = mlrAtivo;
    }
    public MlrUsuarios(int mlrIdUsuarios, String mlrNome, String mlrCpf, Date mlrDataNascimento, String mlrSenha, int mlrNivel, String mlrApelido, String mlrAtivo) {
       this.mlrIdUsuarios = mlrIdUsuarios;
       this.mlrNome = mlrNome;
       this.mlrCpf = mlrCpf;
       this.mlrDataNascimento = mlrDataNascimento;
       this.mlrSenha = mlrSenha;
       this.mlrNivel = mlrNivel;
       this.mlrApelido = mlrApelido;
       this.mlrAtivo = mlrAtivo;
    }
   
     @Id 

    
    @Column(name="mlr_id_usuarios", unique=true, nullable=false)
    public int getMlrIdUsuarios() {
        return this.mlrIdUsuarios;
    }
    
    public void setMlrIdUsuarios(int mlrIdUsuarios) {
        this.mlrIdUsuarios = mlrIdUsuarios;
    }

    
    @Column(name="mlr_nome", nullable=false, length=100)
    public String getMlrNome() {
        return this.mlrNome;
    }
    
    public void setMlrNome(String mlrNome) {
        this.mlrNome = mlrNome;
    }

    
    @Column(name="mlr_cpf", nullable=false, length=14)
    public String getMlrCpf() {
        return this.mlrCpf;
    }
    
    public void setMlrCpf(String mlrCpf) {
        this.mlrCpf = mlrCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mlr_data_nascimento", length=10)
    public Date getMlrDataNascimento() {
        return this.mlrDataNascimento;
    }
    
    public void setMlrDataNascimento(Date mlrDataNascimento) {
        this.mlrDataNascimento = mlrDataNascimento;
    }

    
    @Column(name="mlr_senha", nullable=false, length=50)
    public String getMlrSenha() {
        return this.mlrSenha;
    }
    
    public void setMlrSenha(String mlrSenha) {
        this.mlrSenha = mlrSenha;
    }

    
    @Column(name="mlr_nivel", nullable=false)
    public int getMlrNivel() {
        return this.mlrNivel;
    }
    
    public void setMlrNivel(int mlrNivel) {
        this.mlrNivel = mlrNivel;
    }

    
    @Column(name="mlr_apelido", nullable=false, length=25)
    public String getMlrApelido() {
        return this.mlrApelido;
    }
    
    public void setMlrApelido(String mlrApelido) {
        this.mlrApelido = mlrApelido;
    }

    
    @Column(name="mlr_ativo", nullable=false, length=1)
    public String getMlrAtivo() {
        return this.mlrAtivo;
    }
    
    public void setMlrAtivo(String mlrAtivo) {
        this.mlrAtivo = mlrAtivo;
    }




}


