package bean;
// Generated 11/10/2025 15:20:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MlrVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="mlr_vendas_produtos"
    ,catalog="db_maria_rosa"
)
public class MlrVendasProdutos  implements java.io.Serializable {


     private int mlrIdVendasProdutos;
     private MlrProdutos mlrProdutos;
     private MlrVendas mlrVendas;
     private int mlrQuantidade;
     private Double mlrPrecoUnitario;
     private Double mlrDesconto;
     private Date mlrDataCadastro;

    public MlrVendasProdutos() {
    }

    public MlrVendasProdutos(int mlrIdVendasProdutos, MlrProdutos mlrProdutos, MlrVendas mlrVendas, int mlrQuantidade, Double mlrPrecoUnitario, Double mlrDesconto, Date mlrDataCadastro) {
       this.mlrIdVendasProdutos = mlrIdVendasProdutos;
       this.mlrProdutos = mlrProdutos;
       this.mlrVendas = mlrVendas;
       this.mlrQuantidade = mlrQuantidade;
       this.mlrPrecoUnitario = mlrPrecoUnitario;
       this.mlrDesconto = mlrDesconto;
       this.mlrDataCadastro = mlrDataCadastro;
    }
   
     @Id 

    
    @Column(name="mlr_id_vendas_produtos", unique=true, nullable=false)
    public int getMlrIdVendasProdutos() {
        return this.mlrIdVendasProdutos;
    }
    
    public void setMlrIdVendasProdutos(int mlrIdVendasProdutos) {
        this.mlrIdVendasProdutos = mlrIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mlr_fk_produtos", nullable=false)
    public MlrProdutos getMlrProdutos() {
        return this.mlrProdutos;
    }
    
    public void setMlrProdutos(MlrProdutos mlrProdutos) {
        this.mlrProdutos = mlrProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mlr_fk_vendas", nullable=false)
    public MlrVendas getMlrVendas() {
        return this.mlrVendas;
    }
    
    public void setMlrVendas(MlrVendas mlrVendas) {
        this.mlrVendas = mlrVendas;
    }

    
    @Column(name="mlr_quantidade", nullable=true)
    public int getMlrQuantidade() {
        return this.mlrQuantidade;
    }
    
    public void setMlrQuantidade(int mlrQuantidade) {
        this.mlrQuantidade = mlrQuantidade;
    }

    
    @Column(name="mlr_preco_unitario", nullable=true, precision=10)
    public Double getMlrPrecoUnitario() {
        return this.mlrPrecoUnitario;
    }
    
    public void setMlrPrecoUnitario(Double mlrPrecoUnitario) {
        this.mlrPrecoUnitario = mlrPrecoUnitario;
    }

    
    @Column(name="mlr_desconto", nullable=true, precision=10)
    public Double getMlrDesconto() {
        return this.mlrDesconto;
    }
    
    public void setMlrDesconto(Double mlrDesconto) {
        this.mlrDesconto = mlrDesconto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mlr_data_cadastro", nullable=true, length=10)
    public Date getMlrDataCadastro() {
        return this.mlrDataCadastro;
    }
    
    public void setMlrDataCadastro(Date mlrDataCadastro) {
        this.mlrDataCadastro = mlrDataCadastro;
    }




}


