package bean;
// Generated 11/10/2025 15:20:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MlrVendas generated by hbm2java
 */
@Entity
@Table(name="mlr_vendas"
    ,catalog="db_maria_rosa"
)
public class MlrVendas  implements java.io.Serializable {


     private int mlrIdVendas;
     private MlrClientes mlrClientes;
     private MlrFuncionarios mlrFuncionarios;
     private Date mlrDataVenda;
     private Double mlrTotal;
     private String mlrFormaPagamento;
     private String mlrStatus;

    public MlrVendas() {
    }

	
    public MlrVendas(int mlrIdVendas, MlrClientes mlrClientes, MlrFuncionarios mlrFuncionarios, Date mlrDataVenda, Double mlrTotal, String mlrFormaPagamento, String mlrStatus) {
        this.mlrIdVendas = mlrIdVendas;
        this.mlrClientes = mlrClientes;
        this.mlrFuncionarios = mlrFuncionarios;
        this.mlrDataVenda = mlrDataVenda;
        this.mlrTotal = mlrTotal;
        this.mlrFormaPagamento = mlrFormaPagamento;
        this.mlrStatus = mlrStatus;
    }
    public MlrVendas(int mlrIdVendas, MlrClientes mlrClientes, MlrFuncionarios mlrFuncionarios, Date mlrDataVenda, Double mlrTotal, String mlrFormaPagamento, String mlrStatus, Set mlrVendasProdutoses) {
       this.mlrIdVendas = mlrIdVendas;
       this.mlrClientes = mlrClientes;
       this.mlrFuncionarios = mlrFuncionarios;
       this.mlrDataVenda = mlrDataVenda;
       this.mlrTotal = mlrTotal;
       this.mlrFormaPagamento = mlrFormaPagamento;
       this.mlrStatus = mlrStatus;
    }
   
     @Id 

    
    @Column(name="mlr_id_vendas", unique=true, nullable=false)
    public int getMlrIdVendas() {
        return this.mlrIdVendas;
    }
    
    public void setMlrIdVendas(int mlrIdVendas) {
        this.mlrIdVendas = mlrIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mlr_fk_clientes", nullable=false)
    public MlrClientes getMlrClientes() {
        return this.mlrClientes;
    }
    
    public void setMlrClientes(MlrClientes mlrClientes) {
        this.mlrClientes = mlrClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mlr_fk_funcionarios", nullable=false)
    public MlrFuncionarios getMlrFuncionarios() {
        return this.mlrFuncionarios;
    }
    
    public void setMlrFuncionarios(MlrFuncionarios mlrFuncionarios) {
        this.mlrFuncionarios = mlrFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mlr_data_venda", nullable=false, length=10)
    public Date getMlrDataVenda() {
        return this.mlrDataVenda;
    }
    
    public void setMlrDataVenda(Date mlrDataVenda) {
        this.mlrDataVenda = mlrDataVenda;
    }

    
    @Column(name="mlr_total", nullable=false, precision=10)
    public Double getMlrTotal() {
        return this.mlrTotal;
    }
    
    public void setMlrTotal(Double mlrTotal) {
        this.mlrTotal = mlrTotal;
    }

    
    @Column(name="mlr_forma_pagamento", nullable=false, length=50)
    public String getMlrFormaPagamento() {
        return this.mlrFormaPagamento;
    }
    
    public void setMlrFormaPagamento(String mlrFormaPagamento) {
        this.mlrFormaPagamento = mlrFormaPagamento;
    }

    
    @Column(name="mlr_status", nullable=false, length=50)
    public String getMlrStatus() {
        return this.mlrStatus;
    }
    
    public void setMlrStatus(String mlrStatus) {
        this.mlrStatus = mlrStatus;
    }




}


